# TOML file to configure perf runner

# Name of the project
name = "name-of-project-under-test"

# Path to the project to benchmark
path = "path/to/project-under-test"

projUri = "URI to clone project from"

tag = "version of project"

basePackage = "github.com/pelletier/go-toml/v2"

gcpProject = "your-project-1234"

gcpBucket = "your-bucket"

# This tool needs a custom linux image with access to the Go compiler suite and git
gcpImage = "your-image"

# Benchmark Execution Duration (baseline: 1s) (remove)
bed = 1

# Number of executions of single benchmark during a suite run (baseline: 5) (remove)
it = 1

# Number of suite runs (baseline: 3) (remove)
sr = 1

# Number of instance runs (baseline: 3)
ir = 2
